#!/bin/bash
#SBATCH -N 1 --ntasks-per-node=64
#SBATCH -t 3:00:00
#SBATCH -p RM-shared
#SBATCH -J 'run'
#SBATCH -o '%x.out'
#SBATCH --mail-type=ALL
#SBATCH --mail-user=nasc4134@colorado.edu

#module load gcc
#module load cuda/11.1.1
#module load openmpi/3.1.6-gcc8.3.1
module load gromacs/2018

export GMX_MAXBACKUP=-1  # do not make back-ups
export GMX_MAXCONSTRWARN=-1

#Energy minimization
gmx grompp -f min.mdp -p topol.top -c glycerol.gro -o min.tpr
gmx mdrun -table table.xvg -deffnm min

#NVE (50 ps)
gmx grompp -f grompp.mdp -p topol.top -c min.gro -o run.tpr
gmx mdrun -table table.xvg -deffnm run
